name: Bug report
description: Reporta un bug
title: "[BUG] "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tu reporte. Por favor completa este formulario.
  - type: input
    id: title
    attributes:
      label: Título del problema
      description: Describe brevemente el error
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Describe cómo reproducir el problema
    validations:
      required: true
