name: 🐛 Reporte de Bug
description: Reporta un error o comportamiento inesperado
title: "[BUG] "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Reporte de Bug

        ¡Gracias por tomarte el tiempo de ayudarnos a mejorar!

        Si encontraste un error o algo no funciona como debería, por favor completá el siguiente formulario con la mayor cantidad de información posible.

        ---
        <kbd>🚀 Hacé clic en "Iniciar proceso" para comenzar</kbd>
  - type: input
    id: title
    attributes:
      label: Título del bug
      description: Especificá en pocas palabras cuál es el problema
      placeholder: "Ej: La validación del email no funciona"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Descripción detallada
      description: Contanos exactamente qué pasó. ¿Qué esperabas que suceda y qué sucedió realmente?
      placeholder: "Ej: Cuando ingreso un email inválido y presiono enviar, no aparece ningún mensaje de error..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Lista clara y paso a paso para que podamos reproducir el problema.
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '...'
        3. Ingresar '...'
        4. Ver el error
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Entorno / plataforma
      description: ¿Dónde ocurrió el bug?
      placeholder: "Ej: Chrome 117 / Windows 10 / Versión mobile / API v2.1"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs o capturas de pantalla
      description: Si podés, adjuntá errores de consola, logs o screenshots que ayuden a entender el problema.
      placeholder: "Pegá aquí cualquier mensaje de error relevante, o subí una imagen una vez creado el issue."
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severidad del bug
      description: ¿Qué tanto impacta este bug?
      options:
        - 🟢 Menor – No afecta el funcionamiento general
        - 🟡 Media – Afecta funciones importantes pero con workaround
        - 🔴 Alta – Rompe funcionalidades clave o bloquea el uso
    validations:
      required: true
