name: " Solicitud de requerimiento BI"
description: "Iniciar flujo de requerimiento BI"
title: "[BI - SOLICITUD DE REQUERIMIENTO]"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ##  Solicitud de requerimiento BI
        Por favor completa el siguiente formulario para iniciar el flujo de requerimientos de BI.  
        Esto nos ayudar谩 a organizar, comprender y dar seguimiento de manera clara y efectiva.

  - type: dropdown
    id: tipo_requerimiento
    attributes:
      label: Tipo de requerimiento
      description: Selecciona el tipo de requerimiento que deseas solicitar.
      options:
        - Nueva funcionalidad
        - Actualizaci贸n de funcionalidad
        - Correcci贸n de errores
    validations:
      required: true

  - type: textarea
    id: descripcion_requerimiento
    attributes:
      label:  Descripci贸n del requerimiento
      description: Explic谩 de manera detallada qu茅 se necesita y por qu茅. Esto ayudar谩 a comprender mejor el objetivo del requerimiento.
      placeholder: "Ejemplo: Necesitamos incorporar un nuevo campo en el reporte de ventas para filtrar por regi贸n..."
    validations:
      required: true

  - type: input
    id: documentacion
    attributes:
      label:  Link a la documentaci贸n (si aplica)
      description: Incluye aqu铆 un enlace a documentaci贸n o material de referencia.
      placeholder: "https://ejemplo.com/doc"
    validations:
      required: false

  - type: input
    id: fecha_reunion
    attributes:
      label:  Fecha de reuni贸n para comprensi贸n de requerimientos
      description: Indica una fecha propuesta para la reuni贸n.
      placeholder: "AAAA-MM-DD"
    validations:
      required: false

  - type: checkboxes
    id: info_test
    attributes:
      label: Informaci贸n disponible para pruebas
      description: Marca si ya existe informaci贸n disponible para testear el requerimiento.
      options:
        - label: S铆, hay informaci贸n disponible
        - label: No, a煤n falta preparar informaci贸n

  - type: input
    id: fecha_validacion
    attributes:
      label:  Fecha de validaci贸n del desarrollo
      description: Una vez finalizado el desarrollo, indicar la fecha de validaci贸n acordada.
      placeholder: "AAAA-MM-DD"
    validations:
      required: false

  - type: checkboxes
    id: flujo_produccion
    attributes:
      label: Estado de puesta en producci贸n
      description: Marca cuando el desarrollo est茅 finalizado y listo en producci贸n.
      options:
        - label: En proceso
        - label: Finalizado
